<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TrainingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('trainings')->insert([
            ['t_id' => 'TFG1001', 'training' => 'PROCESS FAILURE MODE and EFFECT ANALYSIS'],
            ['t_id' => 'TFG1002', 'training' => 'TOYOTA PRODUCTION SYSTEM'],
            ['t_id' => 'TFG1003', 'training' => 'TOTAL PRODUCTIVE MAINTENANCE'],
            ['t_id' => 'TFG1004', 'training' => 'TOOLING MANAGEMENT'],
            ['t_id' => 'TFG1005', 'training' => 'NUMBERING SYSTEM'],
            ['t_id' => 'TFG1006', 'training' => 'STATISTICAL PROCESS CONTROL'],
            ['t_id' => 'TFG1007', 'training' => 'OPERATION MANUAL'],
            ['t_id' => 'TFG1008', 'training' => 'INSPECTION MANUAL'],
            ['t_id' => 'TFG1009', 'training' => 'ALAT UKUR SEDERHANA'],
            ['t_id' => 'TFG1010', 'training' => 'DAILY CHECK MAINTENANCE'],
            ['t_id' => 'TFG1011', 'training' => 'FORKLIFT'],
            ['t_id' => 'TFG1012', 'training' => 'SKILL UP'],
            ['t_id' => 'TFG1013', 'training' => 'CLEANER PRODUCTION'],
            ['t_id' => 'TFG1014', 'training' => 'STANDARD QUALITY'],
            ['t_id' => 'TFG1015', 'training' => 'ALAT UKUR LISTRIK'],
            ['t_id' => 'TFG1016', 'training' => 'MENGGAMBAR TEKNIK'],
            ['t_id' => 'TFG1017', 'training' => 'ALAT UKUR MEKANIK'],
            ['t_id' => 'TFG1018', 'training' => 'BONGKAR PASANG MESIN'],
            ['t_id' => 'TFG1019', 'training' => 'HIDROLIK PNEUMATIK'],
            ['t_id' => 'TFG1020', 'training' => 'PROJECT MANAGEMENT'],
            ['t_id' => 'TFG1021', 'training' => 'MEKATRONIKA'],
            ['t_id' => 'TFG1022', 'training' => 'CONTINOUS IMPROVEMENT'],
            ['t_id' => 'TFG1023', 'training' => 'MANUFACTURING MANAGEMENT'],
            ['t_id' => 'TFG1024', 'training' => 'PREDICTIVE MAINTENANCE'],
            ['t_id' => 'TFG1025', 'training' => 'JIG & FIXTURE DESIGN'],
            ['t_id' => 'TFG1026', 'training' => 'INVENTORY MANAGEMENT'],
            ['t_id' => 'TFG1027', 'training' => 'PREVENTIVE MAINTENANCE'],
            ['t_id' => 'TFG1028', 'training' => 'RELIABILITY & MAINTAINABILITY'],
            ['t_id' => 'TFG1029', 'training' => 'ADVANCE PRODUCT QUALITY PLANNING'],
            ['t_id' => 'TFG1030', 'training' => 'ENGINEERING MATERIAL & MANUFACTURING PROCESS'],
            ['t_id' => 'TFG1031', 'training' => 'SISTEM SUSPENSI KENDARAAN'],
            ['t_id' => 'TFG1032', 'training' => 'PEMBEBANAN DINAMIKA SISTEM SUSPENSI KENDARAAN'],
            ['t_id' => 'TFG1033', 'training' => 'DASAR MATERIAL'],
            ['t_id' => 'TFG1034', 'training' => 'MANAJEMEN ARSIP'],
            ['t_id' => 'TFG1035', 'training' => 'KAYABA PRODUCTION SYSTEM'],
            ['t_id' => 'TFG1036', 'training' => 'MANAJEMEN PERGUDANGAN'],
            ['t_id' => 'TFG1037', 'training' => 'STRATEGIC COST REDUCTION'],
            ['t_id' => 'TFG1038', 'training' => 'PART FUNCTION'],
            ['t_id' => 'TFG1039', 'training' => 'BAHASA MANDARIN'],
            ['t_id' => 'TFG1040', 'training' => 'VISUAL BASIC & MS ACCESS'],
            ['t_id' => 'TFG1041', 'training' => 'MICROSOFT WINDOWS ADVANCE'],
            ['t_id' => 'TFG1042', 'training' => 'PROCESS PERFORMANCE MANAGEMENT'],
            ['t_id' => 'TFG1043', 'training' => 'DANA PENSIUN DAN JAMSOSTEK'],
            ['t_id' => 'TFG1044', 'training' => 'MARKETING MANAGEMENT DEVELOPMENT PROGRAM'],
            ['t_id' => 'TFG1045', 'training' => 'STRATEGI PEMASARAN'],
            ['t_id' => 'TFG1046', 'training' => 'TEKNIK CUSTOMER SERVICE'],
            ['t_id' => 'TFG1047', 'training' => 'MANAGEMENT PEMASARAN'],
            ['t_id' => 'TFG1048', 'training' => 'ANALYSIS FINANCIAL STATEMENT'],
            ['t_id' => 'TFG1049', 'training' => 'WINDOWS SERVER CONFIGURATION'],
            ['t_id' => 'TFG1050', 'training' => 'BAAN'],
            ['t_id' => 'TFG1051', 'training' => 'JUNIOR PROGRAMMING'],
            ['t_id' => 'TFG1052', 'training' => 'H/W, PC TECHNOLOGIES ADVANCE'],
            ['t_id' => 'TFG1053', 'training' => 'PROSES PRODUKSI'],
            ['t_id' => 'TFG1054', 'training' => 'ALAT UKUR'],
            ['t_id' => 'TFG1055', 'training' => 'BREVET PAJAK WORKSHOP'],
            ['t_id' => 'TFG1056', 'training' => 'BAAN TOOLS FUNDAMENTAL'],
            ['t_id' => 'TFG1057', 'training' => 'BAAN TOOLS ADVANCE'],
            ['t_id' => 'TFG1058', 'training' => 'BAAN FINANCE ADVANCE'],
            ['t_id' => 'TFG1059', 'training' => 'BAAN MANUFACTURING ADVANCE'],
            ['t_id' => 'TFG1060', 'training' => 'BAAN DISTRIBUTION ADVANCE'],
            ['t_id' => 'TFG1061', 'training' => 'WHY-WHY ANALYSIS'],
            ['t_id' => 'TFG1062', 'training' => 'CARTON BOX DESIGN'],
            ['t_id' => 'TFG1063', 'training' => 'METROLOGI INDUSTRI'],
            ['t_id' => 'TFG1064', 'training' => 'BASIC METALLURGY FOR NON METALLURGIST'],
            ['t_id' => 'TFG1065', 'training' => 'HOISTCRANE'],
            ['t_id' => 'TFG1066', 'training' => 'RISET PEMASARAN'],
            ['t_id' => 'TFG1067', 'training' => 'SIX SIGMA'],
            ['t_id' => 'TFG1068', 'training' => 'LEAD AUDITOR ISO TS 16949'],
            ['t_id' => 'TFG1069', 'training' => 'VENDOR MANAGEMENT'],
            ['t_id' => 'TFG1070', 'training' => 'ABC COSTING'],
            ['t_id' => 'TFG1071', 'training' => 'DEVELOP SUB ORDINAT'],
            ['t_id' => 'TFG1072', 'training' => 'FOREMAN ROLE'],
            ['t_id' => 'TFG1073', 'training' => 'HAND BOOK SAFETY'],
            ['t_id' => 'TFG1074', 'training' => 'PRODUCT KNOWLEDGE'],
            ['t_id' => 'TFG1075', 'training' => 'Q-POINT & ATTENTION'],
            ['t_id' => 'TFG1076', 'training' => 'QUALITY AWARENESS'],
            ['t_id' => 'TFG1077', 'training' => 'SUPERVISORY ROLE'],
            ['t_id' => 'TFG1078', 'training' => 'STOP CALL WAIT'],
            ['t_id' => 'TFG1079', 'training' => 'MEMBACA GAMBAR'],
            ['t_id' => 'TFG1080', 'training' => 'STANDARISASI KERJA (TSK - TSKK)'],
            ['t_id' => 'TFS2001', 'training' => 'PENGISIAN STATISTICAL PROCESS CONTROL'],
            ['t_id' => 'TFS2002', 'training' => 'ALAT UKUR KHUSUS'],
            ['t_id' => 'TFS2003', 'training' => 'WELDING : ARC WELDING, RESISTANT WELDING'],
            ['t_id' => 'TFS2004', 'training' => 'CASTING'],
            ['t_id' => 'TFS2005', 'training' => 'PANTING STEEL, ALUMUNIUM'],
            ['t_id' => 'TFS2006', 'training' => 'GRINDING'],
            ['t_id' => 'TFS2007', 'training' => 'PLATING'],
            ['t_id' => 'TFS2008', 'training' => 'ASSEMBLING'],
            ['t_id' => 'TFS2009', 'training' => 'MACHINING : CNC SPECIAL PROPUSE, MANUAL'],
            ['t_id' => 'TFS2010', 'training' => 'CNC PROGRAMMING'],
            ['t_id' => 'TFS2011', 'training' => 'PROBLEM SOLVING WELD, PAINT, GRIND, PLAT, CAST, MACH'],
            ['t_id' => 'TFS2012', 'training' => 'WASTE WATER TREATMENT'],
            ['t_id' => 'TFS2013', 'training' => 'STANDARIZED WORK COMBINATION TABLE'],
            ['t_id' => 'TFS2014', 'training' => '2D CAD'],
            ['t_id' => 'TFS2015', 'training' => 'TOOLING DESIGN'],
            ['t_id' => 'TFS2016', 'training' => 'MANUFACTURING PROCESS'],
            ['t_id' => 'TFS2017', 'training' => 'DASAR LISTRIK'],
            ['t_id' => 'TFS2018', 'training' => 'ELEKTRONIKA'],
            ['t_id' => 'TFS2019', 'training' => 'PLC'],
            ['t_id' => 'TFS2020', 'training' => 'WIRING PANEL'],
            ['t_id' => 'TFS2021', 'training' => 'PRINTED CIRCUIT BARD (PCB)'],
            ['t_id' => 'TFS2022', 'training' => 'ELEMEN MESIN'],
            ['t_id' => 'TFS2023', 'training' => 'COMPRESSOR'],
            ['t_id' => 'TFS2024', 'training' => 'GENSET'],
            ['t_id' => 'TFS2025', 'training' => 'BOILER'],
            ['t_id' => 'TFS2026', 'training' => 'DESIGN FAILURE MODE AND EFFECT ANALYSIS'],
            ['t_id' => 'TFS2027', 'training' => 'CAE : STRUCTURAL ANALYSIS'],
            ['t_id' => 'TFS2028', 'training' => 'CAE: CASTING SIMULATION ANALYSIS MAGMASOFT'],
            ['t_id' => 'TFS2029', 'training' => 'CAE : DIES AND MOULD DESIGN FOR ALUMUNIUM CASTING'],
            ['t_id' => 'TFS2030', 'training' => 'FINITE ELEMENT'],
            ['t_id' => 'TFS2031', 'training' => 'SPECIAL RUBBER COMPOUND DESIGN'],
            ['t_id' => 'TFS2032', 'training' => '3 D CAD & CAM'],
            ['t_id' => 'TFS2033', 'training' => 'ADVANCE MATERIAL KNOWLEDGE'],
            ['t_id' => 'TFS2034', 'training' => 'TRIZ METHOD'],
            ['t_id' => 'TFS2035', 'training' => 'PRODUCT PATENT & INDUSTRIAL DESIGN'],
            ['t_id' => 'TFS2036', 'training' => 'ARGON WELDING'],
            ['t_id' => 'TFS2037', 'training' => 'HEAT TREATMENT'],
            ['t_id' => 'TFS2038', 'training' => 'PLATING & COATING TECHNOLOGY'],
            ['t_id' => 'TFS2039', 'training' => 'NETWORKING FUNDAMENTAL'],
            ['t_id' => 'TFS2040', 'training' => 'MATERIAL SELECTION'],
            ['t_id' => 'TFS2041', 'training' => 'MANAJEMEN PERSEDIAAN'],
            ['t_id' => 'TFS2042', 'training' => 'MANAJEMEN PENGENDALIAN PRODUKSI'],
            ['t_id' => 'TFS2043', 'training' => 'MANAJEMEN PRODUKSI'],
            ['t_id' => 'TFS2044', 'training' => 'MANAJEMEN PEMBELIAN'],
            ['t_id' => 'TFS2045', 'training' => 'KEPABEANAN'],
            ['t_id' => 'TFS2046', 'training' => 'E D I ( ELECTRONIC DATA INTERCHANGE )'],
            ['t_id' => 'TFS2047', 'training' => 'ENGLISH CORRESPONDENCE'],
            ['t_id' => 'TFS2048', 'training' => 'VENDOR EVALUATION'],
            ['t_id' => 'TFS2049', 'training' => 'CUSTOMER SATISFACTION'],
            ['t_id' => 'TFS2050', 'training' => 'NETWORK ADMINISTRATION'],
            ['t_id' => 'TFS2051', 'training' => 'PENGUPAHAN'],
            ['t_id' => 'TFS2052', 'training' => 'HUMAN RESOURCES OFFICER DEVELOPMENT PROGRAM'],
            ['t_id' => 'TFS2053', 'training' => 'LOSS PREVENTIVE MANAGEMENT'],
            ['t_id' => 'TFS2054', 'training' => 'HUBUNGAN INDUSTRIAL'],
            ['t_id' => 'TFS2055', 'training' => 'EODP  (ENVIRONMENTAL OFFICER DEVELOPMENT PROGRAM )'],
            ['t_id' => 'TFS2056', 'training' => 'PAJAK PENGHASILAN'],
            ['t_id' => 'TFS2057', 'training' => 'MANAJEMEN SUMBER DAYA MANUSIA'],
            ['t_id' => 'TFS2058', 'training' => 'ADMINISTRASI TENAGA KERJA'],
            ['t_id' => 'TFS2059', 'training' => 'UNIT TANGGAP DARURAT ASTRA'],
            ['t_id' => 'TFS2060', 'training' => 'MANAJEMEN SECURITY'],
            ['t_id' => 'TFS2061', 'training' => 'INVESTIGASI SECURITY'],
            ['t_id' => 'TFS2062', 'training' => 'COMMUNITY DEVELOPMENT'],
            ['t_id' => 'TFS2063', 'training' => 'BELA DIRI SECURITY'],
            ['t_id' => 'TFS2064', 'training' => 'PERATURAN UU TENAGA KERJA'],
            ['t_id' => 'TFS2065', 'training' => 'P2K3'],
            ['t_id' => 'TFS2066', 'training' => 'DASAR SECURITY 232 JAM ( GADA PRATAMA )'],
            ['t_id' => 'TFS2067', 'training' => 'KEAMANAN STANDARD SECURITY ASTRA ( KURIKULUM UI )'],
            ['t_id' => 'TFS2068', 'training' => 'HUMAN RESOURCES STRATEGIC'],
            ['t_id' => 'TFS2069', 'training' => 'HRMDP ( HUMAN RESOURCES MANAGER DEVELOPMENT PROGRAM )'],
            ['t_id' => 'TFS2070', 'training' => 'MERANCANG PROGRAM PELATIHAN'],
            ['t_id' => 'TFS2071', 'training' => 'PERENCANAAN DAN PENGEMBANGAN KARIR'],
            ['t_id' => 'TFS2072', 'training' => 'MEASURING CUSTOMER SATISFACTION'],
            ['t_id' => 'TFS2073', 'training' => 'EXPORT IMPORT'],
            ['t_id' => 'TFS2074', 'training' => 'MENGUASAI TEKNIK MENJUAL'],
            ['t_id' => 'TFS2075', 'training' => 'HANDLING CUSTOMER COMPLAINT'],
            ['t_id' => 'TFS2076', 'training' => 'CASH FLOW MANAGEMENT'],
            ['t_id' => 'TFS2077', 'training' => 'AUDIT INTERN'],
            ['t_id' => 'TFS2078', 'training' => 'TEKNIK PENYUSUNAN ANGGARAN'],
            ['t_id' => 'TFS2079', 'training' => 'AKUNTANSI BIAYA'],
            ['t_id' => 'TFS2080', 'training' => 'ABC SYSTEM'],
            ['t_id' => 'TFS2081', 'training' => 'SEMINAR TENTANG PAJAK DAN PERATURAN BARU'],
            ['t_id' => 'TFS2082', 'training' => 'DATABASE MANAGEMENT'],
            ['t_id' => 'TFS2083', 'training' => 'BASIC ACCOUNTING'],
            ['t_id' => 'TFS2084', 'training' => 'PROGRAMMING PB'],
            ['t_id' => 'TFS2085', 'training' => 'ENTERPRISE RESOURCE PLANNING'],
            ['t_id' => 'TFS2086', 'training' => 'CISCO'],
            ['t_id' => 'TFS2087', 'training' => 'ORACLE'],
            ['t_id' => 'TFS2088', 'training' => 'ISO 9000'],
            ['t_id' => 'TFS2089', 'training' => 'ISO GUIDE 25'],
            ['t_id' => 'TFS2090', 'training' => 'KALIBRASI ALAT UKUR'],
            ['t_id' => 'TFS2091', 'training' => 'MSA  ( Measuring System Analysis )'],
            ['t_id' => 'TFS2092', 'training' => 'SPECIAL MEASUREMENT (F/TEST, D/F, dsb)'],
            ['t_id' => 'TFS2093', 'training' => 'RISK MANAGEMENT'],
            ['t_id' => 'TFS2094', 'training' => 'MANAGEMENT ACCOUNTING'],
            ['t_id' => 'TFS2095', 'training' => 'FINON IN MANUFACTURING INDUSTRY'],
            ['t_id' => 'TFS2096', 'training' => 'COST ACCOUNTING'],
            ['t_id' => 'TFS2097', 'training' => 'MODERN COST ANALYSIS & CONTROL SYSTEM'],
            ['t_id' => 'TFS2098', 'training' => 'COST ESTIMATING'],
            ['t_id' => 'TFS2099', 'training' => 'CISCO : SPECIALIZATION SECURITY'],
            ['t_id' => 'TFS2100', 'training' => 'CISCO : SPECIALIZATION VOICE'],
            ['t_id' => 'TFS2101', 'training' => 'ORACLE LANGUAGE'],
            ['t_id' => 'TFS2102', 'training' => 'ORACLE DATABASE ADMINISTRATION'],
            ['t_id' => 'TFS2103', 'training' => 'ORACLE DEVELOPER FORM & REPORTS'],
            ['t_id' => 'TFS2104', 'training' => 'ORACLE DEVELOPER DESIGNER'],
            ['t_id' => 'TFS2105', 'training' => 'ORACLE DEVELOPER APLICATION SERVER'],
            ['t_id' => 'TFS2106', 'training' => 'CRYSTAL REPORT 9.0'],
            ['t_id' => 'TFS2107', 'training' => 'SYSTEM ANALYSIS & DESIGN'],
            ['t_id' => 'TFS2108', 'training' => 'GENERAL AFFAIR TRAINING'],
            ['t_id' => 'TFS2109', 'training' => 'SERVICE & GENERAL MAINTENANCE'],
            ['t_id' => 'TFS2110', 'training' => 'HRD KOMPETENSI'],
            ['t_id' => 'TFS2111', 'training' => 'TEKNIK NEGOSIASI'],
            ['t_id' => 'TFS2112', 'training' => 'AKUNTANSI PERPAJAKAN'],
            ['t_id' => 'TFS2113', 'training' => 'INVENTORY CONTROL SYSTEM'],
            ['t_id' => 'TFS2114', 'training' => 'SUPERVISOR SECURITY'],
            ['t_id' => 'TFS2115', 'training' => 'MANAGER SECURITY'],
            ['t_id' => 'TFS2116', 'training' => 'OPERATION TESTING EQUIPMENT'],
            ['t_id' => 'TFS2117', 'training' => 'INTERNAL QUALITY AUDIT'],
            ['t_id' => 'TFS2118', 'training' => 'AUDIT FOR SUPPLIER'],
            ['t_id' => 'TFS2119', 'training' => 'Programming PL-SQL for ORACLE'],
            ['t_id' => 'TFS2120', 'training' => 'CISCO Fundamental'],
            ['t_id' => 'TFS2121', 'training' => 'CISCO Advance'],
            ['t_id' => 'TFS2122', 'training' => 'DATABASE Fundamental'],
            ['t_id' => 'TFS2123', 'training' => 'DATABASE Advance'],
            ['t_id' => 'TFS2124', 'training' => 'OS : Fundamental'],
            ['t_id' => 'TFS2125', 'training' => 'OS : Advance'],
            ['t_id' => 'TFS2126', 'training' => 'IT AUDIT'],
            ['t_id' => 'TFS2127', 'training' => 'MULTI BODY DYNAMIC SIMULATION'],
            ['t_id' => 'TFS2128', 'training' => 'ASSET MANAGEMENT'],
            ['t_id' => 'TFS2129', 'training' => 'AKUNTANSI MANAJEMEN'],
            ['t_id' => 'TFS2130', 'training' => 'FINANCIAL MODELING FOR CORPORATION BUDGET'],
            ['t_id' => 'TFS2131', 'training' => 'KAYABA PRODUCTION SYSTEM Basic'],
            ['t_id' => 'TFS2132', 'training' => 'SIMULASI Assembling Mur & Baut'],
            ['t_id' => 'TFS2133', 'training' => 'SIMULASI KANBAN'],
            ['t_id' => 'TFS2134', 'training' => 'NEGOTIATION SKILL FOR PURCHASER'],
            ['t_id' => 'TFS2135', 'training' => 'WEB PROGRAMMING'],
            ['t_id' => 'TFS2136', 'training' => 'INDUSTRIAL RELATIONS CERTIFICATION PROFESSIONAL'],
            ['t_id' => 'TFS2137', 'training' => 'PUBLIC RELATIONS'],
            ['t_id' => 'TFS2138', 'training' => 'ACCOUNTING FORUM'],
            ['t_id' => 'TFS2139', 'training' => 'MECHATRONICS'],
            ['t_id' => 'TFS2140', 'training' => 'KARAKTER & SIFAT-SIFAT OLI'],
            ['t_id' => 'TFS2141', 'training' => 'BAAN ODM (OBJECT DATA MANAGEMENT)'],
            ['t_id' => 'TFS2142', 'training' => 'CSR ? AFC & AGC'],
            ['t_id' => 'TFS2143', 'training' => 'HODP (HEALTH OFFICER DEVELOPMENT PROGRAM)'],
            ['t_id' => 'TFS2144', 'training' => 'AUDITOR INTERNAL OHSAS 18001/SMK3'],
            ['t_id' => 'TFS2145', 'training' => 'TEKNOLOGI CASTING'],
            ['t_id' => 'TFS2146', 'training' => 'LAPORAN KEUANGAN BERSTANDAR INTERNASIONAL (IFRS)'],
            ['t_id' => 'TFS2147', 'training' => 'MAINTENANCE FANUC SYSTEM'],
            ['t_id' => 'TFS2148', 'training' => 'SKILL DASAR MAINTENANCE'],
            ['t_id' => 'TFS2149', 'training' => 'PEMROGRAMAN PLC'],
            ['t_id' => 'TFS2150', 'training' => 'COMPOSITE TECHNOLOGY'],
            ['t_id' => 'TFS2151', 'training' => 'WELDING TECHNOLOGY'],
            ['t_id' => 'TFS2152', 'training' => 'INVERTER'],
            ['t_id' => 'TFS2153', 'training' => 'SERVO MOTOR & AMPLIFIER'],
            ['t_id' => 'TFS2154', 'training' => 'PROGRAMMABLE TERMINAL'],
            ['t_id' => 'TFS2155', 'training' => 'RESISTANCE WELDING'],
            ['t_id' => 'TFS2156', 'training' => 'PROCUREMENT FRAUD'],
            ['t_id' => 'TFS2157', 'training' => 'LABORATORY MANAGEMENT'],
            ['t_id' => 'TFS2158', 'training' => 'UKL & UPL (UPAYA PENGELOLAAN LINGKUNGAN & UPAYA PEMANTAUAN LINGKUNGAN)'],
            ['t_id' => 'TFS2159', 'training' => 'PROPER (PROGRAM PENILAIAN PERINGKAT KINERJA PERUSAHAAN DALAM PENGLEOLAAN LINGKUNGAN)'],
            ['t_id' => 'TFS2160', 'training' => 'AUDITOR / LEAD AUDITOR OHSAS 18001'],
            ['t_id' => 'TFS2161', 'training' => 'MPPA (MANAJER PENGENDALIAN PENCEMARAN AIR)'],
            ['t_id' => 'TFS2162', 'training' => 'MANAGER ENERGY'],
            ['t_id' => 'TFS2163', 'training' => 'AUDIT ENERGY'],
            ['t_id' => 'TFS2164', 'training' => 'AUDITOR / LEAD AUDITOR ISO 14001'],
            ['t_id' => 'TFS2165', 'training' => 'AUDITOR / LEAD AUDITOR AGC (ASTRA GREEN COMPANY)'],
            ['t_id' => 'TFS2166', 'training' => 'EPCM - UDARA (ENVIRONMENTAL POLLUTION CONTROL MANAGER - UDARA)'],
            ['t_id' => 'TFS2167', 'training' => 'EPCM B3 (ENVIRONMENTAL POLLUTION CONTROL MANAGER ? BAHAN BERBAHAYA DAN BERACUN)'],
            ['t_id' => 'TFS2168', 'training' => 'AUTO CAD / SOLIDWORKS'],
            ['t_id' => 'TFS2170', 'training' => 'TRAINING NEED ANALYSIS'],
            ['t_id' => 'TFS2171', 'training' => 'HIRAC (Hazard Identification Risk Assestment Risk Control)'],
            ['t_id' => 'TFS2172', 'training' => 'DAILY CYCLE COUNT CKDRM'],
            ['t_id' => 'TFS2173', 'training' => 'EFEKTIFITAS TRAINING'],
            ['t_id' => 'TFS2174', 'training' => 'COMPETENCY TRAINING'],
            ['t_id' => 'TFS2176', 'training' => 'Contractor Safety Management System ( CSMS )'],
            ['t_id' => 'TGG1001', 'training' => 'BASIC TRAINING'],
            ['t_id' => 'TGG1002', 'training' => 'JOB ORIENTATION  A'],
            ['t_id' => 'TGG1003', 'training' => 'JOB ORIENTATION  B'],
            ['t_id' => 'TGG1004', 'training' => 'NEW EMPLOYEE ORIENTATION PROGRAM'],
            ['t_id' => 'TGG1005', 'training' => 'ACHIEVEMENT MOTIVATION TRAINING'],
            ['t_id' => 'TGG1006', 'training' => 'KYT AND SAFETY ENVIRONMENTAL'],
            ['t_id' => 'TGG1007', 'training' => '5 R ( RAPIH, RAWAT, RESIK, RINGKAS DAN RAJIN )'],
            ['t_id' => 'TGG1008', 'training' => 'NEW QCC'],
            ['t_id' => 'TGG1009', 'training' => 'QCC JURY'],
            ['t_id' => 'TGG1010', 'training' => 'AMS (ASTRA MANAGEMENT SISTEM )'],
            ['t_id' => 'TGG1011', 'training' => 'TRAIN THE TRAINERS AMS'],
            ['t_id' => 'TGG1012', 'training' => 'SS (SISTEM SARAN)'],
            ['t_id' => 'TGG1013', 'training' => 'JOB INSTRUCTION'],
            ['t_id' => 'TGG1014', 'training' => 'INTERPERSONAL COMMUNICATION SKILL'],
            ['t_id' => 'TGG1015', 'training' => 'PROBLEM SOLVING AND DECISION MAKING'],
            ['t_id' => 'TGG1016', 'training' => 'PRESENTATION SKILL'],
            ['t_id' => 'TGG1017', 'training' => 'TRAINING FOR TRAINERS'],
            ['t_id' => 'TGG1018', 'training' => 'NEGOTIATION SKILL'],
            ['t_id' => 'TGG1019', 'training' => 'INTERVIEWING SKILL'],
            ['t_id' => 'TGG1020', 'training' => 'RINDAM JAYA'],
            ['t_id' => 'TGG1021', 'training' => 'ASTRA BASIC MANAGEMENT PROGRAM'],
            ['t_id' => 'TGG1022', 'training' => 'ASTRA FIRST LINE MANAGEMENT PROGRAM'],
            ['t_id' => 'TGG1023', 'training' => 'ASTRA MIDDLE MANAGEMENT PROGRAM'],
            ['t_id' => 'TGG1024', 'training' => 'ASTRA GENERAL MANAGEMENT PROGRAM'],
            ['t_id' => 'TGG1025', 'training' => 'MAN MANAGEMENT ASTRA'],
            ['t_id' => 'TGG1026', 'training' => '7 HABITS'],
            ['t_id' => 'TGG1027', 'training' => 'SUPPLY CHAIN MANAGEMENT'],
            ['t_id' => 'TGG1028', 'training' => 'AWARENESS LK3 UNTUK KARYAWAN'],
            ['t_id' => 'TGG1029', 'training' => 'INDUKSI LK3 UNTUK KARYAWAN MAGANG/PKL'],
            ['t_id' => 'TGG1030', 'training' => 'INDUKSI LK3 UNTUK SUPLIER, SUBCONTRACTOR, DAN VISITOR'],
            ['t_id' => 'TGG1031', 'training' => 'CIRCLE LEADER'],
            ['t_id' => 'TGG1032', 'training' => 'AWARENESS ISO / TS 16949'],
            ['t_id' => 'TGG1033', 'training' => 'MANAGING PEOPLE'],
            ['t_id' => 'TGG1034', 'training' => 'SUPERVISI EFECTIVE'],
            ['t_id' => 'TGG1035', 'training' => 'COACHING AND CONSELING'],
            ['t_id' => 'TGG1036', 'training' => 'LEADERSHIP & BUILDING RELATIONSHIP'],
            ['t_id' => 'TGG1037', 'training' => 'CREATIVE THINKING'],
            ['t_id' => 'TGG1038', 'training' => 'SAFETY DOJO'],
            ['t_id' => 'TGG1039', 'training' => 'LOTO'],
            ['t_id' => 'TGG1040', 'training' => 'FIRST AID'],
            ['t_id' => 'TGG1041', 'training' => 'FIRE SAFETY'],
            ['t_id' => 'TGG1042', 'training' => 'SAFETY RIDING'],
            ['t_id' => 'TGG1043', 'training' => 'TANGGAP DARURAT'],
            ['t_id' => 'TGG1044', 'training' => 'KPQ (KAYABA PRINCIPLE QUALITY)'],
            ['t_id' => 'TGG1045', 'training' => 'KESADARAN NORMATIF'],
            ['t_id' => 'TGS2001', 'training' => 'FINANCE FOR NON FINANCE MANAGER'],
            ['t_id' => 'TGS2002', 'training' => 'HR FOR NON HR MANAGER'],
            ['t_id' => 'TGS2003', 'training' => 'SISTEM MANAJEMEN LINGKUNGAN ( SMLK3 )'],
            ['t_id' => 'TGS2004', 'training' => 'INTERNAL QUALITY AUDITOR FOR IATF 16949 : 2016'],
            ['t_id' => 'TGS2005', 'training' => 'INTERNAL  AUDITOR FOR ISO 14001 - OHSAS 18001'],
            ['t_id' => 'TGS2006', 'training' => 'ASTRA PRODUCTION MANAGEMENT FOR SUPERVISOR'],
            ['t_id' => 'TGS2007', 'training' => 'ASTRA PRODUCTION MANAGEMENT FOR FOREMAN'],
            ['t_id' => 'TGS2008', 'training' => 'MS OFFICE'],
            ['t_id' => 'TGS2009', 'training' => 'BAHASA INGGRIS'],
            ['t_id' => 'TGS2010', 'training' => 'BAHASA JEPANG'],
            ['t_id' => 'TGS2011', 'training' => 'S-PROSES'],
            ['t_id' => 'TGS2012', 'training' => 'ACTION PLAN CORE VALUE'],
            ['t_id' => 'TGS2013', 'training' => 'INCIDENT INVESTIGATION'],
            ['t_id' => 'TGS2014', 'training' => 'NLP  (NEURO LINGUISTIC PROGRAMING )'],
            ['t_id' => 'TGS2015', 'training' => 'TIME MANAGEMENT'],
            ['t_id' => 'TGS2016', 'training' => 'INSPECTOR LK3 & LEGAL'],
            ['t_id' => 'TGS2017', 'training' => 'CHEMICAL HANDLING'],
            ['t_id' => 'TGS2018', 'training' => 'FIRE RISK MANAGEMENT'],
            ['t_id' => 'TGS2019', 'training' => 'BBSM (BEHAVIOUR BASE SAFETY MANAGEMENT)'],
            ['t_id' => 'TGS2020', 'training' => 'ERGONOMI'],
            ['t_id' => 'TGS2021', 'training' => 'ZARDS (PHYSIC, ELECTRICAL, MECHANICAL, CHEMICAL, BIOLOGICAL)'],
            ['t_id' => 'TGS2022', 'training' => 'OCCUPATIONAL HEALTH & HYGIENE'],
            ['t_id' => 'TGS2023', 'training' => 'MOTOR LISTRIK DAN INVERTER'],
            ['t_id' => 'TGS2024', 'training' => 'SEGREGASI LIMBAH'],
            ['t_id' => 'TGS2025', 'training' => 'AHLI K3'],
        ]);
    }
}
